# Generated by Django 2.2.7 on 2019-12-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20191127_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Remaks_five',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Remaks_four',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Remaks_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Remaks_three',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='Remaks_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
